# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Graph
version:      0.86
version_from: lib/Graph.pm
installdirs:  site
requires:
    List::Util:                    0
    Math::Complex:                 0
    Scalar::Util:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
